ZeonPropertiesListing/ZeonPropertiesListing/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZeonPropertiesListing.Models;
using PagedList;
using System.Data.Entity;

namespace ZeonPropertiesListing.Controllers
{
    [SessionExpire]
    public class BlogController : Controller
    {
        Overriding_DBEntities db = new Overriding_DBEntities();
        // GET: Blog
        #region Display Blog
        public ActionResult DisplayBlog(string searchString, int? page)
        {
            ViewBag.CurrentFilter = searchString;
            var displayBlog = from b in db.L_BlogTbl
                                 select b;
            if (!String.IsNullOrEmpty(searchString))
            {

                displayBlog = displayBlog.Where(b => b.BlogTitle.ToLower().Contains(searchString));
                   
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(displayBlog.OrderByDescending(s => s.CreatedDate).ToPagedList(pageNumber, pageSize));
        }

        #endregion

        #region Delete Blog
        [HttpPost]
        public ActionResult DeleteBlog(int id)
        {
            var blogID = db.L_BlogTbl.Where(x => x.Id == id).FirstOrDefault();

            if (blogID != null)
            {
                if (blogID.Photo != null)
                {
                    var img = blogID.Photo;
                    // delete physical IMAGE from folder
                    string filePath = Server.MapPath(Url.Content("~" + img));
                    if (System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                    }
                }

                db.L_BlogTbl.Remove(blogID);
                db.SaveChanges();


            }
            

            return RedirectToAction("DisplayBlog");
        }
        #endregion

        #region Edit
        public ActionResult Edit(int? id)//id get from  URL 
        {

            if (id == null)
            {
                return RedirectToAction("DisplayBlog");
            }
            else
            {
                var blog = db.L_BlogTbl.Where(x => x.Id == id).FirstOrDefault();
                return View(blog);
            }
        }


        [HttpPost]
        [ValidateInput(false)]//require for ckeditor
        public ActionResult Edit(L_BlogTbl blg, string descripEditor1, string descripEditor2, string descripEditor3)
        {



            if (ModelState.IsValid)
            {



                blg.CreatedDate = DateTime.Now;
                string descript1 = descripEditor1.ToString();
                if (!string.IsNullOrEmpty(descript1))
                {
                    blg.Description1 = descript1;
                }

                string descript2 = descripEditor2.ToString();
                if (!string.IsNullOrEmpty(descript2))
                {
                    blg.Description2 = descript2;
                }

                string descript3 = descripEditor3.ToString();
                if (!string.IsNullOrEmpty(descript3))
                {
                    blg.Description3 = descript3;
                }
                db.Entry(blg).State = EntityState.Modified;
                db.SaveChanges();

                Session["Photo"] = blg.Photo;



                return RedirectToAction("DisplayBlog");
            }

            return View(blg);

            #endregion
        }
        #region create blog
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]//require for ckeditor
        public ActionResult Index(L_BlogTbl blog)
        {
            L_BlogTbl create = new L_BlogTbl();

            create.BlogTitle = blog.BlogTitle;
            create.Description1 = blog.Description1;
            create.Description2 = blog.Description2;
            create.Description3 = blog.Description3;
            create.PostedBy = blog.PostedBy;
            create.CreatedDate = DateTime.Now;
            create.Photo = blog.Photo;

            db.L_BlogTbl.Add(create);
            db.SaveChanges();
            return View();
        }

        #endregion

        #region Upload Image 
        [HttpPost]
        public string UploadBlogImage()
        {
            string path;
            var insertedById = System.Web.HttpContext.Current.Request.Params["InsertedById"];
            var original = System.Web.HttpContext.Current.Request.Params["Original"];

            //Get the uploaded attachment from the Files collection
            HttpPostedFile httpPostedFile = System.Web.HttpContext.Current.Request.Files["UploadedAttached"];

            // Precaution in case if no excel files found
            if (httpPostedFile == null)
            {
                var msg = original;

                return msg;
            }

            var fileName = System.IO.Path.GetFileName(httpPostedFile.FileName);
            string strExtensionName = System.IO.Path.GetExtension(fileName);

            //generate random number
            Random generator = new Random();
            long r = generator.Next(0, 999999999);
            string s = r.ToString("D6");
            fileName = s + strExtensionName;

            for (var i = 0; i < 99; i++)
            {
                FileInfo fileInfo = new FileInfo(Path.Combine(Server.MapPath("/BlogImage/"), fileName));
                if (fileInfo.Exists)
                {
                    //generate random number
                    Random generator2 = new Random();
                    long r2 = generator2.Next(0, 999999999);
                    string s2 = r2.ToString("D6");
                    fileName = s2 + strExtensionName;
                }

                else
                {
                    break;
                }
            }

            // Get the complete file path for temp file
            path = Path.Combine(System.Web.HttpContext.Current.Server.MapPath("/BlogImage"), fileName);

            // Save the uploaded file as temp file
            httpPostedFile.SaveAs(path);

            return "/BlogImage/" + fileName;
        }
        #endregion

        #region Edit Image
        [HttpPost]
        public string EditImage()
        {

            string path;
            var insertedById = System.Web.HttpContext.Current.Request.Params["InsertedById"];
            var original = System.Web.HttpContext.Current.Request.Params["Original"];

            //Get the uploaded attachment from the Files collection
            HttpPostedFile httpPostedFile = System.Web.HttpContext.Current.Request.Files["UploadedAttached"];

            // Precaution in case if no excel files found
            if (httpPostedFile == null)
            {
                var msg = original;

                return msg;
            }

            var fileName = System.IO.Path.GetFileName(httpPostedFile.FileName);
            string strExtensionName = System.IO.Path.GetExtension(fileName);

            //generate random number
            Random generator = new Random();
            long r = generator.Next(0, 999999999);
            string s = r.ToString("D6");
            fileName = s + strExtensionName;

            for (var i = 0; i < 99; i++)
            {
                FileInfo fileInfo = new FileInfo(Path.Combine(Server.MapPath("/BlogImage/"), fileName));
                if (fileInfo.Exists)
                {
                    //generate random number
                    Random generator2 = new Random();
                    long r2 = generator2.Next(0, 999999999);
                    string s2 = r2.ToString("D6");
                    fileName = s2 + strExtensionName;
                }

                else
                {
                    break;
                }
            }

            // Get the complete file path for temp file
            path = Path.Combine(System.Web.HttpContext.Current.Server.MapPath("/BlogImage"), fileName);

            // Save the uploaded file as temp file
            httpPostedFile.SaveAs(path);

            return "/BlogImage/" + fileName;
        }

        #endregion
    }
}

ZeonPropertiesListing/ZeonPropertiesListing/Views/Blog/DisplayBlog.cshtml
@using ZeonPropertiesListing.Models;
@using PagedList;
@using PagedList.Mvc;
@model IPagedList <L_BlogTbl>

@{

    Layout = "~/Views/Shared/DashboardLayout.cshtml";
}

@*@{

        //Html.Partial("_checkLogin");
        ViewBag.Title = "displayData";

        int i = 1;


        if (Session["isAdmin"] == null || Session["isAdmin"] == "")// <- this method is not safe
        {

            //do nothing
            ViewBag.displayStyle = "notAdmin";
        }

        var blogauthor = Session["isAdmin"].ToString();
        if (blogauthor == "3")
        {
            ViewBag.BlogAuthor = "blogauthor";
        }
        else
        {

            var userId = Session["isAdmin"].ToString();
            if (userId == "1")
            {
                ViewBag.displayStyle = "";
            }
            else
            {
                ViewBag.displayStyle = "notAdmin";
            }
        }

    }*@

<br />
<br /> <br /> @* this, break *@

<div style="display:none">
    ID: @Session["isLoginID"], Position:  @Session["usrPosition"] ,Name: @Session["loginUsrName"], Contact: @Session["usrContact"],
    Admin: @Session["isAdmin"]

</div>


<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Required meta tags-->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="au theme template">
<meta name="author" content="Hau Nguyen">
<meta name="keywords" content="au theme template">
<!-- Title Page-->
<title>Dashboard</title>
<!-- Fontfaces CSS-->

<link href="~/CoolAdmin-master/css/font-face.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" />

<!-- Bootstrap CSS-->
<link href="~/CoolAdmin-master/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" />


<!-- Vendor CSS-->
@*<link href="~/CoolAdmin-master/vendor/animsition/animsition.min.css" rel="stylesheet" />*@
<link href="~/CoolAdmin-master/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/wow/animate.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/slick/slick.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/select2/select2.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" />


<!-- Main CSS-->
<link href="~/CoolAdmin-master/css/theme.css" rel="stylesheet" />
<style>
    td {
        font-size: 10px;
    }
</style>

<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>







<!-- MAIN CONTENT-->


<div class="page-wrapper">
    <div class="page-container">
        <div class="row" style="padding-top:20px" ;>

            @if (ViewBag.BlogAuthor == "blogauthor")//if user is normal agent
            {
                <div class="col-md-2">


                    <a href='@Url.Action("CreateBlog", "Listing")' class="btn btn-primary" style="background-color:orange; border-style:none;font-size:15px; width: 160px;height:45px;padding: 10px;"> Create Blog </a>


                </div>
            }




        </div>
        @using (Html.BeginForm("DisplayBlog", "Blog", FormMethod.Get))
        {


            <div class="main-content" style="padding-top:20px" ;>

                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8" style="padding-bottom:20px">

                        <div class="form-header" action="" method="POST">
                            @*search AdsTitle*@
                            @Html.TextBox("searchString", ViewBag.CurrentFilter as string,
                            new { @class = "form-control", placeholder = "Search by Blog Title", style = "height:45px; width:900px; font-size:17px;" })

                        </div>

                    </div>
                    <div class="col-md-2"></div>

                </div>

                <br />





                <div class="row">
                    <div class="col-md-5"></div>

                    <div class="col-md-2">
                        <button class="btn btn-success" type="submit" style="width:200px; height:45px; font-size:17px;">
                            Search
                        </button>
                    </div>

                    <div class="col-md-5"></div>
                </div>




                <br />




                <div class="row">
                    <div class="col-md-12">
                        <!-- DATA TABLE -->


                        <div class="table-responsive table-responsive-data2">
                            <table class="table table-data2">
                                <thead style="background-color:#fd0000bf">
                                    <tr>
                                        <th><label style="font-weight: bold;color:white">Blog ID</label></th>
                                        <th><label style="font-weight: bold;color:white">Blog Title</label></th>
                                        <th><label style="font-weight: bold;color:white">Created Date</label></th>
                                        <th><label style="font-weight: bold;color:white">Posted By</label></th>
                                        <th><label style="font-weight: bold;color:white">Edit</label></th>
                                        <th><label style="font-weight: bold;color:white">Delete</label></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.Count() > 0)
                                    {

                                        foreach (var item in Model)
                                        {

                                            <tr class="tr-shadow">
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Id)
                                                </td>
                                                <td>@Html.DisplayFor(modelItem => item.BlogTitle)</td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.CreatedDate, "{0:dd/MM/yyyy HH:mm:ss}")
                                                </td>



                                                <td>@Html.DisplayFor(modelItem => item.PostedBy)</td>

                                                <td>
                                                    @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "fa fa-edit", title = "Edit", style = "font-size: 25px; color:green;" }) <span>&nbsp;</span> <span>&nbsp;</span>
                                                </td>
                                                <td>
                                                    <a class="modal-trigger fa fa-trash" href="#" data-toggle="modal"
                                                       value="@item.Id" onclick="passToModal(this)" data-target="#myModal" style="font-size:25px; color:red;" title="Delete Property Listing"></a>

                                                </td>

                                            </tr>

                                        }//end foreach
                                    }//end if  has row/result
                                    else
                                    {
                                        <tr><td><strong>No Result</strong></td></tr>
                                    } @*end else*@
                                </tbody>
                            </table>
                        </div>
                    </div>

                    @Html.PagedListPager(Model, page => Url.Action("DisplayBlog", "Blog", new { page, searchString = ViewBag.CurrentFilter}))


                </div>
                @* MODAL STRUCTURE *@
                <div class="modal fade" id="myModal">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div style="background-color:salmon;" class="modal-header">

                                <h3 style="color:white;">Delete Blog</h3><a href="#" class="close" data-dismiss="modal"> &times; </a>
                            </div>
                            <div class="modal-body">
                                <h4>Are you sure you want to delete this Blog? </h4>
                                <br />
                                Any images and attachment uploaded in this Listing will be removed.
                                <input style="display:none" type="text" id="blogIdd" />
                            </div> @* end modal-body *@
                            <div class="modal-footer">
                                <a href="#" class="btn btn-danger" data-dismiss="modal"> Cancel </a>
                                <input type="submit" value="Confirm" class="btn btn-success" id="btnSubmit" />
                            </div> @* end modal-footer *@

                        </div> @* end modal-content *@
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="copyright">
                            <p>&copy; @DateTime.Now.Year - Zeon Properties Sdn Bhd </p>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

</div>


<script type="text/javascript" src="~/Scripts/displayBlog.js"></script>

@Html.Hidden("delBlog", Url.Action("DeleteBlog", "Blog")) @* pass to displayDataJS *@




<!-- END MAIN CONTENT-->
<!-- Jquery JS-->
@*<script src="~/CoolAdmin-master/vendor/jquery-3.2.1.min.js"></script>*@

<!-- Bootstrap JS-->
<script src="~/CoolAdmin-master/vendor/bootstrap-4.1/popper.min.js"></script>
<script src="~/CoolAdmin-master/vendor/bootstrap-4.1/bootstrap.min.js"></script>

<!-- Vendor JS       -->
<script src="~/CoolAdmin-master/vendor/slick/slick.min.js"></script>
<script src="~/CoolAdmin-master/vendor/wow/wow.min.js"></script>
@*<script src="~/CoolAdmin-master/vendor/animsition/animsition.min.js"></script>*@
<script src="~/CoolAdmin-master/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<script src="~/CoolAdmin-master/vendor/counter-up/jquery.waypoints.min.js"></script>
<script src="~/CoolAdmin-master/vendor/counter-up/jquery.counterup.min.js"></script>
<script src="~/CoolAdmin-master/vendor/circle-progress/circle-progress.min.js"></script>
<script src="~/CoolAdmin-master/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
<script src="~/CoolAdmin-master/vendor/chartjs/Chart.bundle.min.js"></script>
<script src="~/CoolAdmin-master/vendor/select2/select2.min.js"></script>

<!-- Main JS-->
@*<script src="~/CoolAdmin-master/js/main.js"></script>*@

ZeonPropertiesListing/ZeonPropertiesListing/Views/Blog/Edit.cshtml
@model ZeonPropertiesListing.Models.L_BlogTbl

@{
    
    //Html.Partial("_checkLogin");

}
@{

    Layout = "~/Views/Shared/DashboardLayout.cshtml";
}
<h2>Create New Listing</h2>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>


@*<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>*@
<!-- Required meta tags-->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="au theme template">
<meta name="author" content="Hau Nguyen">
<meta name="keywords" content="au theme template">

<!-- Fontfaces CSS-->

<link href="~/CoolAdmin-master/css/font-face.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" />

<!-- Bootstrap CSS-->
<link href="~/CoolAdmin-master/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" />


<!-- Vendor CSS-->
<link href="~/CoolAdmin-master/vendor/animsition/animsition.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/wow/animate.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/slick/slick.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/select2/select2.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" />


<!-- Main CSS-->
<link href="~/CoolAdmin-master/css/theme.css" rel="stylesheet" />


<h2>Create Blog</h2>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script>
    function UploadImage() {
        //showLoader("Importing Machines from Excel file. Might take a moment depending on data size..");

        var data = new FormData();
        var files = $("#image_attached").get(0).files;

        // Add the uploaded image content to the form data collection
        if (files.length > 0) {
            data.append("UploadedAttached", files[0]);
            data.append("InsertedById", "Admin");
        }
        else {
            var files = $("#Photo").get(0).files;
            data.append("UploadedAttached", files[0]);
            data.append("InsertedById", "Admin");
        }

        // Make Ajax request with the contentType = false, and procesDate = false and async = false
        $.ajax({
            url: "/Blog/EditImage",
            data: data,
            type: "POST",
            async: false,
            contentType: false,
            processData: false,
            success: function (result) {
                $('#Photo').val(result);
            },
            error: function (xhr, status, error) { }
        });
    }

    function someFunc() {

        UploadImage();

    }
</script>

<div>

</div>


<!-- MAIN CONTENT-->
<div class="page-wrapper">
    <div class="page-container">

        <div class="main-content" style="padding-top:50px">




            @using (Html.BeginForm("Edit", "Blog", FormMethod.Post))
            {
                @* @Html.AntiForgeryToken() this cause _checkLogin error *@


                <div class="form-horizontal" style="">

                    <div class="row">
                        <div class="form-group col-md-12">

                            <div class="col-md-5">
                                @Html.LabelFor(model => model.Photo, "Blog Photo", htmlAttributes: new {
                                          style= " margin-left: -11px;",
                                          @class = "control-label" })<br />
                                <img src="@Html.DisplayFor(model => model.Photo)" style="min-width:240px;max-width:240px; min-height:240px;max-height:240px;font-family: 'Montserrat', sans-serif;font-weight: 500;font-style: normal;font-size: 9px;line-height: 23px;letter-spacing: 0.03em;color: #707070;text-transform: uppercase;display: block;" alt="Photo will be shown here after uploaded." />
                                <input type="file" name="image_attached" id="image_attached" /> <br /> <br />
                                @*<button type="button" value="@Html.DisplayFor(model => model.EmployeeImg)" class="btn btn-danger" onclick="delImg(this)">Delete</button>*@
                                @Html.TextBoxFor(model => model.Photo, new { @class = "form-control hidden", style = "display:none" })
                            </div>
                        </div>
                        <div class="form-group col-md-12">
                            <div class="col-md-5">
                                @Html.LabelFor(model => model.BlogTitle, htmlAttributes: new {
                                     style= " margin-left: -11px;",
                                     @class = "control-label" })
                                <label style="color:red;">*</label>
                            </div>
                            <div class="">
                                @Html.TextBoxFor(model => model.BlogTitle, new { id = "blogtitle", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.BlogTitle, "", new { @class = "text-danger" })


                            </div>
                        </div>
                        <div class="form-group col-md-12">
                            <div class="col-md-5">
                                @Html.LabelFor(model => model.Description1, htmlAttributes:
                               new { style = "margin-left: -11px;", @class = "control-label" })
                            </div>

                            <div class="">
                                @Html.TextAreaFor(model => model.Description1,
                               new {id="description1",@class = "ckeditor", @Name = "descripEditor1" })
                                @Html.ValidationMessageFor(model => model.Description1, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group col-md-12">
                            <div class="col-md-5">
                                @Html.LabelFor(model => model.Description2, htmlAttributes:
                               new { style = "margin-left: -11px;", @class = "control-label" })
                            </div>

                            <div class="">
                                @Html.TextAreaFor(model => model.Description2,
                               new {id="description2",@class = "ckeditor", @Name = "descripEditor2" })
                                @Html.ValidationMessageFor(model => model.Description2, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group col-md-12">
                            <div class="col-md-5">
                                @Html.LabelFor(model => model.Description3, htmlAttributes:
                               new { style = "margin-left: -11px;", @class = "control-label" })
                            </div>

                            <div class="">
                                @Html.TextAreaFor(model => model.Description3,
                               new {id="description3",@class = "ckeditor", @Name = "descripEditor3" })
                                @Html.ValidationMessageFor(model => model.Description3, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <div class="col-md-12">
                                @Html.LabelFor(model => model.PostedBy, htmlAttributes:
                               new { style = "margin-left: -30px;", @class = "control-label col-md-2" })
                            </div>
                            <div class="">
                                @Html.TextBoxFor(model => model.PostedBy, new { @class = "form-control", @readonly = "readonly" })
                                @Html.ValidationMessageFor(model => model.PostedBy, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        @* Create Button *@
                        <div class="col-md-offset-0 col-md-6" style="text-align:center; margin-top:10px;">
                            <input id="createbtn" type="submit" value="Edit" name="submitbtn"
                                   style="height: 40px; width: 140px;" class="btn btn-default btn-primary" onclick="someFunc();" />
                        </div>

                    </div>



                </div>



                <input type="text" style="display:none" name="clickedBtn" id="clickedBtn" />
            }@* End begin form *@




            <div>
                @Html.ActionLink("Back to List", "displayData")
            </div>






        </div>
    </div>
</div>
<!-- END MAIN CONTENT-->
<!-- Jquery JS-->
<script src="~/CoolAdmin-master/vendor/jquery-3.2.1.min.js"></script>

<!-- Bootstrap JS-->
<script src="~/CoolAdmin-master/vendor/bootstrap-4.1/popper.min.js"></script>
<script src="~/CoolAdmin-master/vendor/bootstrap-4.1/bootstrap.min.js"></script>

<!-- Vendor JS       -->
<script src="~/CoolAdmin-master/vendor/slick/slick.min.js"></script>
<script src="~/CoolAdmin-master/vendor/wow/wow.min.js"></script>
<script src="~/CoolAdmin-master/vendor/animsition/animsition.min.js"></script>
<script src="~/CoolAdmin-master/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<script src="~/CoolAdmin-master/vendor/counter-up/jquery.waypoints.min.js"></script>
<script src="~/CoolAdmin-master/vendor/counter-up/jquery.counterup.min.js"></script>
<script src="~/CoolAdmin-master/vendor/circle-progress/circle-progress.min.js"></script>
<script src="~/CoolAdmin-master/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
<script src="~/CoolAdmin-master/vendor/chartjs/Chart.bundle.min.js"></script>
<script src="~/CoolAdmin-master/vendor/select2/select2.min.js"></script>

<!-- Main JS-->
<script src="~/CoolAdmin-master/js/main.js"></script>