ZeonPropertiesListing/ZeonPropertiesListing/Controllers/ListingController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core.Objects; //for EntityFunctions.TruncateTime in DisplayData()
using System.Data.Entity.Validation;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZeonPropertiesListing.Controllers;
using ZeonPropertiesListing.Models;//(1) [projectName][Model]
using ZeonPropertiesListing.ViewModel;
//Go to Nuget -> Browse -> "EPPlus" -> using OfficeOpenXml
using OfficeOpenXml;
using PagedList;
namespace Listing.Controllers
{
    //this is important. This enable multiple ajax to send to controller. 
    //this also affect session. Any session declare in this controller may not function as expected
    [SessionExpire]
    public class ListingController : Controller
    {
        Overriding_DBEntities db = new Overriding_DBEntities();
        // GET: Listing
        //This will route to displayData View when user enter Listing/ only
        //[Route("Listing/")]

        public ActionResult displayData(string searchString, int? page, string PropertyTypeDashB,
                    string agentDashB, string stateDashB, string LTypeDashB, string StatusDashB, string areaDashB)
        {//(2) display every data from database

            using (Overriding_DBEntities dbModel = new Overriding_DBEntities())
            {




                //this is to make sure when another page is clicked, system will remember the enetered/selected values in filter part
                //return searched AdsTitle 
                ViewBag.CurrentFilter = searchString;
                //return property type to textbox etc
                ViewBag.currentpropertyType = PropertyTypeDashB;
                ViewBag.currentAgent = agentDashB;
                ViewBag.currentState = stateDashB;
                ViewBag.currentLType = LTypeDashB;
                ViewBag.currentStatus = StatusDashB;
                ViewBag.currentArea = areaDashB;

                //Note:
                /*
                 currentFilter -> capture from 
                 */
                //Property Type
                List<string> PropertyTypeList = new List<string>();
                PropertyTypeList.Add("Bungalow"); PropertyTypeList.Add("Terrace House");
                PropertyTypeList.Add("Semi Detached"); PropertyTypeList.Add("Apartment");
                PropertyTypeList.Add("Cluster Home"); PropertyTypeList.Add("Factory");
                PropertyTypeList.Add("Industrial Land"); PropertyTypeList.Add("Development Land");
                PropertyTypeList.Add("Agriculture Land"); PropertyTypeList.Add("Shop House");
                PropertyTypeList.Add("Complex Shoplot"); PropertyTypeList.Add("Office Lot");
                PropertyTypeList.Add("Town House"); PropertyTypeList.Add("Others");
                PropertyTypeList.Sort();

                ViewBag.PropertyType = new SelectList(PropertyTypeList, PropertyTypeDashB);

                //return filtered agent
                ViewBag.Agent = agentDashB;

                //return filtered  AddedDateDashB = DateTime.Today;
                var AddedDateDashB = Request.Form["AddedDateDashB"];
                ViewBag.compleDate = AddedDateDashB;

                //return filtered listing type
                List<string> Ltype = new List<string>();
                Ltype.Add("Rent"); Ltype.Add("Sale"); Ltype.Add("Rent & Sale");
                Ltype.Sort();
                ViewBag.Ltype = new SelectList(Ltype, LTypeDashB);

                //return filtered state
                ViewBag.DrpDownState = dbModel.L_State_tb.Where(x => !string.IsNullOrEmpty(x.StateName)).Distinct().ToList();
                //return filtered status
                List<string> StatusType = new List<string>();
                StatusType.Add("Approved"); StatusType.Add("Taken Down"); StatusType.Add("Pending");
                StatusType.Sort();

                //Note: usually a 0 is use to initialize a int var. Since 0 is used as "take down" 
                //hence it is initialzie with 10 instead    
                var statusInt = 10;
                ViewBag.StatusType = new SelectList(StatusType, StatusDashB);
                if (StatusDashB == "Approved") { statusInt = 1; }
                else if (StatusDashB == "Taken Down") { statusInt = 0; }
                else if (StatusDashB == "Pending") { statusInt = -1; }




                //Start search/filter
                var agentDashboard = from s in dbModel.v_listing.Where(x => x.Status != -2)//exclude draft
                                     select s;


                var AllAgents = new List<v_listing>();


                if (!String.IsNullOrEmpty(searchString))
                {
                    string[] agents = searchString.Split(' ');
                    foreach (var name in agents)
                    {
                        agentDashboard = agentDashboard.Where(s => s.FirstName.ToLower().Contains(name) | s.LastName.ToLower().Contains(name) | s.AdsTitle.Contains(searchString) | s.UserID.Contains(searchString) | s.UnitNo.Contains(searchString));
                        AllAgents.AddRange(agentDashboard);
                    }
                    //agentDashboard = agentDashboard.Where(s => s.AdsTitle.Contains(searchString) || s.FirstName.Contains(searchString) || s.LastName.Contains(searchString) || s.UserID.Contains(searchString));
                }
                if (!String.IsNullOrEmpty(PropertyTypeDashB))
                {
                    agentDashboard = agentDashboard.Where(s => s.PropertyType.Contains(PropertyTypeDashB));
                }
                if (!String.IsNullOrEmpty(agentDashB))
                {
                    agentDashboard = agentDashboard.Where(s => s.Agent == agentDashB);
                }
                if (!String.IsNullOrEmpty(LTypeDashB))
                {
                    agentDashboard = agentDashboard.Where(s => s.ListingType == LTypeDashB);
                }
                if (!String.IsNullOrEmpty(stateDashB))
                {
                    agentDashboard = agentDashboard.Where(s => s.State == stateDashB);
                }
                if (statusInt != 10)
                {
                    agentDashboard = agentDashboard.Where(s => s.Status == statusInt);
                }
                if (!String.IsNullOrEmpty(AddedDateDashB))
                {
                    //This retrive AddedDate (Date+Time) -> TruncateTime = Cut out the time part, left the date -> turn to string -> compare by 'Contain'
                    agentDashboard = agentDashboard.Where(s => EntityFunctions.TruncateTime(s.AddedDate).ToString().Contains(AddedDateDashB));

                }


                if (!String.IsNullOrEmpty(areaDashB))
                {
                    agentDashboard = agentDashboard.Where(s => s.Area.Contains(areaDashB));
                }
                //save to session. These session will be use to filtered again before export to Excel
                Session["search"] = searchString;
                Session["propertyType"] = PropertyTypeDashB;
                Session["agent"] = agentDashB;
                Session["AddedDate"] = AddedDateDashB;
                Session["state"] = stateDashB;
                Session["ListingType"] = LTypeDashB;
                Session["status"] = StatusDashB;
                Session["area"] = areaDashB;

                int pageSize = 30;
                int pageNumber = (page ?? 1);

                TempData["currentPg"] = pageNumber;//current page number asign to tempdata




                return View(agentDashboard.Where(x => x.UnitStatus == "Vacant").OrderByDescending(s => s.AddedDate).ToPagedList(pageNumber, pageSize));
            }
        }


        public JsonResult loadArea(string stateName)
        {
            using (Overriding_DBEntities dbModel = new Overriding_DBEntities())
            {
                var stateID = dbModel.L_State_tb.Where(x => x.StateName == stateName).Select(x => x.StateID).FirstOrDefault();

                return Json(dbModel.L_Area_tb.Where(a => a.StateID == stateID).Select(a => new {
                    aName = a.AreaName
                }).ToList(), JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ExportToExcel()
        {
            //call session from displayData()
            var search = Session["search"];
            var propertyType = Session["propertyType"];
            var agent = Session["agent"];
            var AddedDate = Session["AddedDate"];
            var state = Session["state"];
            var area = Session["area"];
            var ListingType = Session["ListingType"];
            var status = Session["status"];


            using (Overriding_DBEntities dbModel = new Overriding_DBEntities())
            {
                //start include filtered data
                var agentDashboard = from s in dbModel.v_listing.Where(x => x.Status != -2)//exclude draft
                                     select s;


                //filtered ads title
                if (!String.IsNullOrEmpty(search as string))
                {
                    agentDashboard = agentDashboard.Where(s => s.AdsTitle.Contains(search.ToString()) | s.UnitNo.Contains(search.ToString()) | s.UserID.Contains(search.ToString())
                    | s.FirstName.Contains(search.ToString()) | s.LastName.Contains(search.ToString()));
                }
                //filtered property type
                if (!String.IsNullOrEmpty(propertyType as string))
                {
                    agentDashboard = agentDashboard.Where(s => s.PropertyType.Contains(propertyType.ToString()));
                }


                //filtered listing type
                if (!String.IsNullOrEmpty(ListingType as string))
                {

ZeonPropertiesListing/ZeonPropertiesListing/Views/Listing/NoJS.cshtml
@{

    Layout = "~/Views/Shared/DashboardLayout.cshtml";
}
<h1>This browser has No Javascript. Please enable Javascript in this browser</h1>

ZeonPropertiesListing/ZeonPropertiesListing/Views/Listing/myDraft.cshtml
@model IEnumerable<ZeonPropertiesListing.Models.L_ListingTbl>

@{
    ViewBag.Title = "myDraft";
    //Html.Partial("_checkLogin");

    var str = Session["isLoginID"];
    ViewBag.Id = str.ToString();
}

@{

    Layout = "~/Views/Shared/DashboardLayout.cshtml";
}

<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<!-- Fontfaces CSS-->

<link href="~/CoolAdmin-master/css/font-face.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" />

<!-- Bootstrap CSS-->
<link href="~/CoolAdmin-master/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" />


<!-- Vendor CSS-->
<link href="~/CoolAdmin-master/vendor/animsition/animsition.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/wow/animate.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/slick/slick.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/select2/select2.min.css" rel="stylesheet" />
<link href="~/CoolAdmin-master/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" />


<!-- Main CSS-->
<link href="~/CoolAdmin-master/css/theme.css" rel="stylesheet" />
@*<link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@

<div class="page-wrapper">
    <div class="page-container">

        <div class="main-content" style="margin-left:15px;padding-top:20px">
            <h2>My Draft</h2>

            <p>
                @Html.ActionLink("Create New", "Create")
            </p>

            <br /><br /><br />


            @foreach (var item in Model)
            {


                <div class="row" style="border-style: solid; border-width: 2px; border-color: coral;">
                    <div class="col-md-10">

                        @{
                            if (string.IsNullOrEmpty(item.AdsTitle))
                            {
                                <strong><span style="color:gray">[NO TITLE]</span> </strong>
                            }
                            else
                            {
                                @Html.DisplayFor(modelItem => item.AdsTitle)
                            }
                        }


                        <strong>
                            (
                            @if (string.IsNullOrEmpty(item.PropertyType))
                            {
                                <strong><span style="color:gray">[No Property Type]</span> </strong>
                            }
                            else
                            {
                                @Html.DisplayFor(modelItem => item.PropertyType)
                            }
                            )
                        </strong>


                        <p>  @Html.DisplayFor(modelItem => item.AddedDate) &nbsp; | &nbsp; @Html.DisplayFor(modelItem => item.Agent)</p>
                    </div>
                    <div class="col-md-2">
                        <div class="row">
                            <div class="col">  @Html.ActionLink("Edit", "Draft", new { id = item.Id }) </div>|
                            <div class="col">
                                @using (Html.BeginForm())
                                {
                                    //this is a button, style and become hyperlink
                                    @*<button type="submit" formaction="/Listing/Delete" value="@item.Id" name="deldraft"
                                                class="btn btn-link" role="link"
                                                style="height: 10px; line-height: 1.4px; margin-top:-5px; font-weight:500;">
                                            Delete
                                        </button>*@

                                    <a class="modal-trigger" href="#" data-toggle="modal"
                                       value="@item.Id" onclick="passToModal(this)" data-target="#myModal">Delete</a>
                                }

                            </div>
                        </div>



                    </div>

                </div>

            }


            @* MODAL STRUCTURE *@
            <div class="modal fade" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div style="background-color:salmon;" class="modal-header">

                            <h3 style="color:white;">Delete Listing</h3><a href="#" class="close" data-dismiss="modal"> &times; </a>
                        </div>
                        <div class="modal-body">
                            <h4>Are you sure you want to delete this Draft? </h4>
                            <br />
                            Any images and attachment uploaded in this Draft will be removed.
                            <input style="display:none;" type="text" id="listingIdd" />
                        </div> @* end modal-body *@
                        <div class="modal-footer">
                            <a href="#" class="btn btn-danger" data-dismiss="modal"> Cancel </a>
                            <input type="submit" value="Confirm" class="btn btn-success" id="btnSubmit" />
                        </div> @* end modal-footer *@

                    </div> @* end modal-content *@
                </div>
            </div>

            @Html.Hidden("delListing", Url.Action("Delete", "Listing")) @* pass to script *@


        </div>
    </div>
</div>
<!-- END MAIN CONTENT-->

<noscript>

    <meta http-equiv="refresh" content="0;URL=http://42.1.63.244/Listing/NoJS" />


</noscript>
<script type="text/javascript">
    //pass ID from button to modal when onclick delete link
    function passToModal(lnk) {
        var val = lnk.getAttribute('value');//get vaue from delete link
        document.getElementById('listingIdd').value = val;//display in textbox in modal
    }

    //Modal's Confirm button: get ID from button -> delete
    $("#btnSubmit").click(function () {

        var urlurl = $("#delListing").val();//get url
        var listingId = $("#listingIdd").val();//get id

        $.ajax({
            type: "POST",
            url: urlurl,
            data: { id: listingId },
            success: function () {
                $("#myModal").modal("hide");
                console.log("Success delete");
                location.reload();//reload page
            },
            error: function (x, e) { //xhr, status, p3, p4

                if (x.status == 0) {
                    console.log('You are offline!!\n Please Check Your Network.');
                } else if (x.status == 404) {
                    console.log('Requested URL not found.');
                } else if (x.status == 500) {
                    console.log('Internel Server Error.');
                } else if (e == 'parsererror') {
                    console.log('Error.\nParsing JSON Request failed.');
                } else if (e == 'timeout') {
                    console.log('Request Time out.');
                } else {
                    console.log('Unknow Error.\n' + x.responseText);
                }
            }

        })
    })//end btnSubmit
</script>